import sys
import random
from PyQt5 import uic
from PyQt5.QtGui import QPainter, QColor
from PyQt5.QtWidgets import QApplication, QWidget

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/User/AppData/Local/Temp/UIwdsEcy.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MyWidgetUiForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(542, 496)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setObjectName("btn")
        self.horizontalLayout.addWidget(self.btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.canvas = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setText("")
        self.canvas.setObjectName("canvas")
        self.verticalLayout.addWidget(self.canvas)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Git и желты окружности"))
        self.btn.setText(_translate("Form", "Draw"))


class MyWidgetWindow(MyWidgetUiForm, QWidget):
    def __init__(self):
        super(MyWidgetWindow, self).__init__()
        self.setupUi(self)

        self.btn.clicked.connect(self.btn_clicked)

        self.do_paint = False

    def paintEvent(self, event):
        if self.do_paint:
            qp = QPainter()
            qp.begin(self)
            self.draw_circle(qp)
            qp.end()

    def btn_clicked(self):
        self.do_paint = True
        self.repaint()

    def draw_circle(self, qp):
        r = random.randint(1, min(self.height(), self.width()) // 2)
        x, y = random.randint(r, self.width() - r), \
               random.randint(r, self.height() - r)

        qp.setBrush(QColor(random.randint(0, 255),
                           random.randint(0, 255),
                           random.randint(0, 255)))
        qp.drawEllipse(x, y, r, r)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidgetWindow()
    ex.show()
    sys.exit(app.exec())
